apiVersion: v1
kind: BuildConfig
metadata:
    labels:
        app: python-nginx-pipeline2
    name: python-nginx-pipeline2
spec:
    source:
        git:
            ref: master
            uri: https://github.com/candrabiondi/openshift-python-pipeline.git
    strategy:
        jenkinsPipelineStrategy:
            jenkinsfilePath: openshift/pipelines/Jenkinsfile
        type: JenkinsPipeline
    triggers:
        - github:
            secret: secret
          type: GitHub
        - generic:
            secret: secret
          type: Generic
        - bitbucket:
            secret: secret
          type: Bitbucket
